# Generated by Django 3.2.5 on 2021-09-09 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_bookinstance_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='date_of_death',
            new_name='died',
        ),
    ]
