# Generated by Django 3.2.5 on 2021-09-09 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_date_of_death_author_died'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='died',
            new_name='date_of_death',
        ),
    ]
