# Generated by Django 3.2.5 on 2021-10-08 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_videoproxy_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='Video_id',
            new_name='video_id',
        ),
    ]
