# Generated by Django 3.2.5 on 2021-10-11 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0005_alter_playlist_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='videos',
        ),
    ]
